# Generated by Django 4.0.6 on 2022-07-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flyings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('wh', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('co', models.IntegerField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
    ]
